GpgFrontend::UI::GnuPGControllerDialog Class Reference
Public Slots
void SlotAccept ()
Signals
void SignalRestartNeeded (int)
Public Member Functions
GnuPGControllerDialog (QWidget *parent=nullptr)
Construct a new General Tab object.
Private Slots
void slot_set_restart_needed (int)
void slot_update_custom_key_database_path_label (int state)
void slot_update_custom_gnupg_install_path_label (int state)
Private Member Functions
auto get_restart_needed () const -> int
Get the Restart Needed object.
void set_settings ()
Set the settings object.
void apply_settings ()
auto check_custom_gnupg_path (QString) -> bool
auto check_custom_gnupg_key_database_path (QString) -> bool
Private Attributes
std::shared_ptr< Ui_GnuPGControllerDialog > ui_
int restart_needed_ {0}
QString custom_key_database_path_
QString custom_gnupg_path_
Additional Inherited Members
Constructor & Destructor Documentation
GnuPGControllerDialog()
GpgFrontend::UI::GnuPGControllerDialog::GnuPGControllerDialog (QWidget * parent = nullptr) [explicit]
Construct a new General Tab object.
Parameters
parent
References GpgFrontend::UI::UISignalStation::GetInstance(), SignalRestartNeeded(), and slot_set_restart_needed().
Member Function Documentation
check_custom_gnupg_key_database_path()
auto GpgFrontend::UI::GnuPGControllerDialog::check_custom_gnupg_key_database_path (QString path) -> bool [private]
Returns
true
false
check_custom_gnupg_path()
auto GpgFrontend::UI::GnuPGControllerDialog::check_custom_gnupg_path (QString path) -> bool [private]
Returns
true
false
get_restart_needed()
int GpgFrontend::UI::GnuPGControllerDialog::get_restart_needed () const -> int [private]
Get the Restart Needed object.
Returns
true
false
SignalRestartNeeded
void GpgFrontend::UI::GnuPGControllerDialog::SignalRestartNeeded (int) [signal]
Parameters
needed
Referenced by GnuPGControllerDialog().
slot_set_restart_needed
void GpgFrontend::UI::GnuPGControllerDialog::slot_set_restart_needed (int mode) [private], [slot]
Parameters
needed
Referenced by GnuPGControllerDialog().
The documentation for this class was generated from the following files:
src/ui/dialog/gnupg/GnuPGControllerDialog.h
src/ui/dialog/gnupg/GnuPGControllerDialog.cpp