GpgFrontend::GpgContext Class Reference
Classes
struct _ctx_ref_deleter
Signals
void SignalNeedUserInputPassphrase ()
Public Member Functions
GpgContext (const GpgContextInitArgs &args={})
Construct a new Gpg Context object.
GpgContext (int channel)
Construct a new Gpg Context object.
~GpgContext () override=default
Destroy the Gpg Context object.
bool good () const
const GpgInfo & GetInfo (bool refresh=false)
Get the Info object.
operator gpgme_ctx_t () const
void SetPassphraseCb (gpgme_passphrase_cb_t func) const
Set the Passphrase Cb object.
Static Public Member Functions
static gpgme_error_t test_passphrase_cb (void *opaque, const char *uid_hint, const char *passphrase_info, int last_was_bad, int fd)
static gpgme_error_t custom_passphrase_cb (void *opaque, const char *uid_hint, const char *passphrase_info, int last_was_bad, int fd)
static gpgme_error_t test_status_cb (void *hook, const char *keyword, const char *args)
Private Types
using CtxRefHandler = std::unique_ptr< struct gpgme_context, _ctx_ref_deleter >
Private Member Functions
void post_init_ctx ()
std::string need_user_input_passphrase ()
std::optional< std::string > check_binary_chacksum (std::filesystem::path)
Construct a new std::check component existence object.
Private Attributes
GpgInfo info_
GpgContextInitArgs args_
bool extend_info_loaded_ = false
CtxRefHandler _ctx_ref = nullptr
bool good_ = true
Additional Inherited Members
Constructor & Destructor Documentation
GpgContext() [1/2]
GpgFrontend::GpgContext::GpgContext (const GpgContextInitArgs & args = {}) [explicit]
Construct a new Gpg Context object.
Parameters
args Constructor Set up gpgme-context, set paths to app-run path
References GpgFrontend::GpgInfo::AppPath, GpgFrontend::check_gpg_error(), GpgFrontend::check_gpg_error_2_err_code(), GpgFrontend::SingletonFunctionObject< TaskRunnerGetter >::GetInstance(), and post_init_ctx().
GpgContext() [2/2]
GpgFrontend::GpgContext::GpgContext (int channel) [explicit]
Construct a new Gpg Context object.
Parameters
channel
Member Function Documentation
custom_passphrase_cb()
gpgme_error_t GpgFrontend::GpgContext::custom_passphrase_cb (void * opaque, const char * uid_hint, const char * passphrase_info, int last_was_bad, int fd) [static]
Parameters
opaque
uid_hint
passphrase_info
last_was_bad
fd
Returns
gpgme_error_t
References GpgFrontend::CoreCommonUtil::GetInstance(), GpgFrontend::SingletonFunctionObject< GpgContext >::GetInstance(), GpgFrontend::CoreCommonUtil::GetTempCacheValue(), and need_user_input_passphrase().
Referenced by post_init_ctx().
GetInfo()
const GpgInfo & GpgFrontend::GpgContext::GetInfo (bool refresh = false)
Get the Info object.
Returns
const GpgInfo&
References check_binary_chacksum(), GpgFrontend::GpgCommandExecutor::Execute(), and GpgFrontend::SingletonFunctionObject< GpgCommandExecutor >::GetInstance().
Referenced by GpgFrontend::UI::GnupgTab::GnupgTab(), post_init_ctx(), and GpgFrontend::UI::CommonUtils::SlotExecuteGpgCommand().
good()
bool GpgFrontend::GpgContext::good () const
Returns
true
false
need_user_input_passphrase()
std::string GpgFrontend::GpgContext::need_user_input_passphrase () [private]
Returns
std::string
References GpgFrontend::CoreSignalStation::GetInstance().
Referenced by custom_passphrase_cb().
operator gpgme_ctx_t()
GpgFrontend::GpgContext::operator gpgme_ctx_t () const [inline]
Returns
gpgme_ctx_t
post_init_ctx()
void GpgFrontend::GpgContext::post_init_ctx () [private]
Setting the output type must be done at the beginning
think this means ascii-armor --> ?
Setting the output type must be done at the beginning
think this means ascii-armor --> ?
References GpgFrontend::GpgInfo::AppPath, GpgFrontend::check_gpg_error(), GpgFrontend::check_gpg_error_2_err_code(), custom_passphrase_cb(), GetInfo(), GpgFrontend::CoreSignalStation::GetInstance(), SetPassphraseCb(), test_passphrase_cb(), and test_status_cb().
Referenced by GpgContext().
SetPassphraseCb()
void GpgFrontend::GpgContext::SetPassphraseCb (gpgme_passphrase_cb_t func) const
Set the Passphrase Cb object.
Parameters
func
Referenced by post_init_ctx().
test_passphrase_cb()
gpgme_error_t GpgFrontend::GpgContext::test_passphrase_cb (void * opaque, const char * uid_hint, const char * passphrase_info, int last_was_bad, int fd) [static]
Parameters
opaque
uid_hint
passphrase_info
last_was_bad
fd
Returns
gpgme_error_t
Referenced by post_init_ctx().
test_status_cb()
gpgme_error_t GpgFrontend::GpgContext::test_status_cb (void * hook, const char * keyword, const char * args) [static]
Parameters
hook
keyword
args
Returns
gpgme_error_t
Referenced by post_init_ctx().
The documentation for this class was generated from the following files:
src/core/GpgContext.h
src/core/GpgContext.cpp