GpgFrontend::UI::SignersPicker Class Reference
Public Member Functions
SignersPicker (QWidget *parent=nullptr)
Construct a new Signers Picker object.
GpgFrontend::KeyIdArgsListPtr GetCheckedSigners ()
Get the Checked Signers object.
bool GetStatus () const
Private Attributes
KeyList * key_list_
bool accepted_ = false
Constructor & Destructor Documentation
SignersPicker()
GpgFrontend::UI::SignersPicker::SignersPicker (QWidget * parent = nullptr) [explicit]
Construct a new Signers Picker object.
Parameters
parent
References GpgFrontend::UI::KeyList::AddListGroupTab(), and GpgFrontend::GpgKey::IsHasActualSigningCapability().
Member Function Documentation
GetCheckedSigners()
GpgFrontend::KeyIdArgsListPtr GpgFrontend::UI::SignersPicker::GetCheckedSigners ()
Get the Checked Signers object.
Returns
GpgFrontend::KeyIdArgsListPtr
References GpgFrontend::UI::KeyList::GetPrivateChecked().
GetStatus()
bool GpgFrontend::UI::SignersPicker::GetStatus () const
Returns
The documentation for this class was generated from the following files:
src/ui/dialog/SignersPicker.h
src/ui/dialog/SignersPicker.cpp