GpgFrontend::UI::KeyImportDetailDialog Class Reference
Public Member Functions
KeyImportDetailDialog (std::shared_ptr< GpgImportInformation > result, QWidget *parent=nullptr)
Construct a new Key Import Detail Dialog object.
Private Member Functions
void create_general_info_box ()
Create a general info box object.
void create_keys_table ()
Create a keys table object.
void create_button_box ()
Create a button box object.
Static Private Member Functions
static auto get_status_string (int) -> QString
Get the status string object.
Private Attributes
QTableWidget * keys_table_ {}
QGroupBox * general_info_box_ {}
QGroupBox * key_info_box_ {}
QDialogButtonBox * button_box_ {}
std::shared_ptr< GpgImportInformation > m_result_
Additional Inherited Members
Constructor & Destructor Documentation
KeyImportDetailDialog()
GpgFrontend::UI::KeyImportDetailDialog::KeyImportDetailDialog (std::shared_ptr< GpgImportInformation > result, QWidget * parent = nullptr) [explicit]
Construct a new Key Import Detail Dialog object.
Parameters
result
automatic
parent
References create_button_box(), create_general_info_box(), and create_keys_table().
Member Function Documentation
get_status_string()
auto GpgFrontend::UI::KeyImportDetailDialog::get_status_string (int key_status) -> QString [static], [private]
Get the status string object.
Parameters
keyStatus
Returns
QString
Referenced by create_keys_table().
The documentation for this class was generated from the following files:
ui/dialog/import_export/KeyImportDetailDialog.h
ui/dialog/import_export/KeyImportDetailDialog.cpp