GpgFrontend::UI::GeneralTab Class Reference
Signals
void SignalRestartNeeded (bool needed)
void SignalDeepRestartNeeded (bool needed)
Public Member Functions
GeneralTab (QWidget *parent=nullptr)
Construct a new General Tab object.
void SetSettings ()
Set the Settings object.
void ApplySettings ()
Private Attributes
std::shared_ptr< Ui_GeneralSettings > ui_
std::vector< std::string > key_ids_list_
KeyList * m_key_list_ {}
Constructor & Destructor Documentation
GeneralTab()
GpgFrontend::UI::GeneralTab::GeneralTab (QWidget * parent = nullptr) [explicit]
Construct a new General Tab object.
Parameters
parent
References GpgFrontend::SingletonFunctionObject< GlobalSettingStation >::GetInstance(), GpgFrontend::GlobalSettingStation::GetUISettings(), and GpgFrontend::UI::SettingsDialog::ListLanguages().
Member Function Documentation
SignalDeepRestartNeeded
void GpgFrontend::UI::GeneralTab::SignalDeepRestartNeeded (bool needed) [signal]
Parameters
needed
Referenced by GpgFrontend::UI::SettingsDialog::SettingsDialog().
SignalRestartNeeded
void GpgFrontend::UI::GeneralTab::SignalRestartNeeded (bool needed) [signal]
Parameters
needed
Referenced by GpgFrontend::UI::SettingsDialog::SettingsDialog().
The documentation for this class was generated from the following files:
src/ui/dialog/settings/SettingsGeneral.h
src/ui/dialog/settings/SettingsGeneral.cpp