GpgFrontend::Thread::CtxCheckTask Class Reference
Signals
void SignalGnupgNotInstall ()
Public Member Functions
CtxCheckTask ()
Construct a new Ctx Check Thread object.
Protected Member Functions
void Run () override
Run - run the task.
Additional Inherited Members
Constructor & Destructor Documentation
CtxCheckTask()
GpgFrontend::Thread::CtxCheckTask::CtxCheckTask ()
Construct a new Ctx Check Thread object.
Copyright (C) 2021 Saturneric
This file is part of GpgFrontend.
GpgFrontend is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
GpgFrontend is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with GpgFrontend. If not, see https://www.gnu.org/licenses/.
The initial version of the source code is inherited from the gpg4usb project, which is under GPL-3.0-or-later.
The source code version of this software was modified and released by Saturneric eric@bktus.com eric@bktus.com starting on May 12, 2021.
References GpgFrontend::CoreCommonUtil::GetInstance().
Member Function Documentation
Run()
void GpgFrontend::Thread::CtxCheckTask::Run () [override], [protected], [virtual]
Run - run the task.
Reimplemented from GpgFrontend::Thread::Task.
References GpgFrontend::GpgKeyGetter::FlushKeyCache(), GpgFrontend::SingletonFunctionObject< GpgContext >::GetInstance(), GpgFrontend::SingletonFunctionObject< GpgKeyGetter >::GetInstance(), and GpgFrontend::init_logging().
The documentation for this class was generated from the following files:
src/core/thread/CtxCheckTask.h
src/core/thread/CtxCheckTask.cpp