GpgFrontend::UI::SetOwnerTrustLevel Class Reference
Public Member Functions
SetOwnerTrustLevel (QWidget *parent)
Set the Owner Trust Level object.
auto Exec (const QString &key_id) -> bool
Constructor & Destructor Documentation
SetOwnerTrustLevel()
GpgFrontend::UI::SetOwnerTrustLevel::SetOwnerTrustLevel (QWidget * parent) [explicit]
Set the Owner Trust Level object.
Parameters
parent
Member Function Documentation
Exec()
auto GpgFrontend::UI::SetOwnerTrustLevel::Exec (const QString & key_id) -> bool
Parameters
key_id
Returns
true
false
References GpgFrontend::UI::UISignalStation::GetInstance(), GpgFrontend::SingletonFunctionObject< GpgKeyGetter >::GetInstance(), and GpgFrontend::SingletonFunctionObject< GpgKeyManager >::GetInstance().
Referenced by GpgFrontend::UI::KeyMgmt::create_actions().
The documentation for this class was generated from the following files:
src/ui/function/SetOwnerTrustLevel.h
src/ui/function/SetOwnerTrustLevel.cpp