GpgFrontend::GpgKeyOpera Class Reference
Public Member Functions
GpgKeyOpera (int channel=SingletonFunctionObject::GetDefaultChannel())
Construct a new Gpg Key Opera object.
void DeleteKeys (KeyIdArgsListPtr key_ids)
void DeleteKey (const KeyId &key_id)
auto SetExpire (const GpgKey &key, const SubkeyId &subkey_fpr, std::unique_ptr< QDateTime > &expires) -> GpgError
Set the Expire object.
void GenerateRevokeCert (const GpgKey &key, const QString &output_path)
void ModifyPassword (const GpgKey &key, const GpgOperationCallback &)
auto ModifyTOFUPolicy (const GpgKey &key, gpgme_tofu_policy_t tofu_policy) -> GpgFrontend::GpgError
void GenerateKey (const std::shared_ptr< GenKeyInfo > &, const GpgOperationCallback &)
auto GenerateKeySync (const std::shared_ptr< GenKeyInfo > &params) -> std::tuple< GpgError, DataObjectPtr >
void GenerateSubkey (const GpgKey &key, const std::shared_ptr< GenKeyInfo > &params, const GpgOperationCallback &)
auto GenerateSubkeySync (const GpgKey &key, const std::shared_ptr< GenKeyInfo > &params) -> std::tuple< GpgError, DataObjectPtr >
void GenerateKeyWithSubkey (const std::shared_ptr< GenKeyInfo > &params, const std::shared_ptr< GenKeyInfo > &subkey_params, const GpgOperationCallback &callback)
auto GenerateKeyWithSubkeySync (const std::shared_ptr< GenKeyInfo > &params, const std::shared_ptr< GenKeyInfo > &subkey_params) -> std::tuple< GpgError, DataObjectPtr >
Private Attributes
GpgContext & ctx_
Additional Inherited Members
Constructor & Destructor Documentation
GpgKeyOpera()
GpgFrontend::GpgKeyOpera::GpgKeyOpera (int channel = SingletonFunctionObject::GetDefaultChannel()) [explicit]
Construct a new Gpg Key Opera object.
Parameters
channel
Member Function Documentation
DeleteKey()
void GpgFrontend::GpgKeyOpera::DeleteKey (const KeyId & key_id)
Parameters
key_id
References DeleteKeys().
DeleteKeys()
void GpgFrontend::GpgKeyOpera::DeleteKeys (KeyIdArgsListPtr key_ids)
Parameters
key_ids Delete keys
uidList key ids
References GpgFrontend::CheckGpgError(), and GpgFrontend::SingletonFunctionObject< GpgKeyGetter >::GetInstance().
Referenced by DeleteKey().
GenerateKey()
void GpgFrontend::GpgKeyOpera::GenerateKey (const std::shared_ptr< GenKeyInfo > & params, const GpgOperationCallback & callback)
Parameters
params
result
Returns
GpgFrontend::GpgError
Generate a new key pair
Parameters
params key generation args
Returns
error information
References GpgFrontend::CheckGpgError(), and GpgFrontend::RunGpgOperaAsync().
GenerateKeySync()
auto GpgFrontend::GpgKeyOpera::GenerateKeySync (const std::shared_ptr< GenKeyInfo > & params) -> std::tuple<GpgError, DataObjectPtr>
Parameters
params
References GpgFrontend::CheckGpgError(), and GpgFrontend::RunGpgOperaSync().
GenerateKeyWithSubkey()
void GpgFrontend::GpgKeyOpera::GenerateKeyWithSubkey (const std::shared_ptr< GenKeyInfo > & params, const std::shared_ptr< GenKeyInfo > & subkey_params, const GpgOperationCallback & callback)
Parameters
params
subkey_params
callback
References GpgFrontend::CheckGpgError(), GpgFrontend::SingletonFunctionObject< GpgKeyGetter >::GetInstance(), and GpgFrontend::RunGpgOperaAsync().
GenerateKeyWithSubkeySync()
auto GpgFrontend::GpgKeyOpera::GenerateKeyWithSubkeySync (const std::shared_ptr< GenKeyInfo > & params, const std::shared_ptr< GenKeyInfo > & subkey_params) -> std::tuple<GpgError, DataObjectPtr>
Parameters
params
subkey_params
callback
References GpgFrontend::CheckGpgError(), GpgFrontend::SingletonFunctionObject< GpgKeyGetter >::GetInstance(), and GpgFrontend::RunGpgOperaSync().
GenerateRevokeCert()
void GpgFrontend::GpgKeyOpera::GenerateRevokeCert (const GpgKey & key, const QString & output_path)
Parameters
key
output_file_name Generate revoke cert of a key pair
key target key pair
outputFileName out file name(path)
Returns
the process doing this job
References GpgFrontend::GpgCommandExecutor::ExecuteSync(), and GpgFrontend::GpgKey::GetFingerprint().
GenerateSubkey()
void GpgFrontend::GpgKeyOpera::GenerateSubkey (const GpgKey & key, const std::shared_ptr< GenKeyInfo > & params, const GpgOperationCallback & callback)
Parameters
key
params
Returns
GpgFrontend::GpgError
References GpgFrontend::CheckGpgError(), GpgFrontend::GpgKey::GetId(), and GpgFrontend::RunGpgOperaAsync().
GenerateSubkeySync()
auto GpgFrontend::GpgKeyOpera::GenerateSubkeySync (const GpgKey & key, const std::shared_ptr< GenKeyInfo > & params) -> std::tuple<GpgError, DataObjectPtr>
Parameters
key
params
References GpgFrontend::CheckGpgError(), and GpgFrontend::RunGpgOperaSync().
ModifyPassword()
void GpgFrontend::GpgKeyOpera::ModifyPassword (const GpgKey & key, const GpgOperationCallback & callback)
Parameters
key
Returns
GpgFrontend::GpgError
References GpgFrontend::RunGpgOperaAsync().
ModifyTOFUPolicy()
auto GpgFrontend::GpgKeyOpera::ModifyTOFUPolicy (const GpgKey & key, gpgme_tofu_policy_t tofu_policy) -> GpgFrontend::GpgError
Parameters
key
tofu_policy
Returns
GpgFrontend::GpgError
References GpgFrontend::CheckGpgError(), and GpgFrontend::CompareSoftwareVersion().
SetExpire()
auto GpgFrontend::GpgKeyOpera::SetExpire (const GpgKey & key, const SubkeyId & subkey_fpr, std::unique_ptr< QDateTime > & expires) -> GpgError
Set the Expire object.
Parameters
key
subkey_fpr
expires
Returns
GpgError
Set the expire date and time of a key pair(actually the primary key) or subkey
Parameters
key target key pair
subkey null if primary key
expires date and time
Returns
if successful
Member Data Documentation
ctx_
GpgContext& GpgFrontend::GpgKeyOpera::ctx_ [private]
Initial value:
=
      GpgContext::GetInstance(SingletonFunctionObject::GetChannel())
The documentation for this class was generated from the following files:
src/core/function/gpg/GpgKeyOpera.h
src/core/function/gpg/GpgKeyOpera.cpp