GpgFrontend::GpgKeyManager Class Reference
Classes
struct AutomatonHandelStruct
Public Member Functions
GpgKeyManager (int channel=SingletonFunctionObject::GetDefaultChannel())
Construct a new Gpg Key Manager object.
bool SignKey (const GpgKey &target, KeyArgsList &keys, const std::string &uid, const std::unique_ptr< boost::posix_time::ptime > &expires)
Sign a key pair(actually a certain uid)
bool RevSign (const GpgFrontend::GpgKey &key, const GpgFrontend::SignIdArgsListPtr &signature_id)
bool SetExpire (const GpgKey &key, std::unique_ptr< GpgSubKey > &subkey, std::unique_ptr< boost::posix_time::ptime > &expires)
Set the Expire object.
bool SetOwnerTrustLevel (const GpgKey &key, int trust_level)
Private Types
using Command = std::string
using AutomatonState = enum { AS_START, AS_COMMAND, AS_VALUE, AS_REALLY_ULTIMATE, AS_SAVE, AS_ERROR, AS_QUIT, }
using AutomatonActionHandler = std::function< Command(AutomatonHandelStruct &, AutomatonState)>
using AutomatonNextStateHandler = std::function< AutomatonState(AutomatonState, std::string, std::string)>
Static Private Member Functions
static gpgme_error_t interactor_cb_fnc (void *handle, const char *status, const char *args, int fd)
Private Attributes
GpgContext & ctx_
Additional Inherited Members
Constructor & Destructor Documentation
GpgKeyManager()
GpgFrontend::GpgKeyManager::GpgKeyManager (int channel = SingletonFunctionObject::GetDefaultChannel()) [explicit]
Construct a new Gpg Key Manager object.
Parameters
channel Copyright (C) 2021 Saturneric
This file is part of GpgFrontend.
GpgFrontend is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
GpgFrontend is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with GpgFrontend. If not, see https://www.gnu.org/licenses/.
The initial version of the source code is inherited from the gpg4usb project, which is under GPL-3.0-or-later.
All the source code of GpgFrontend was modified and released by Saturneric eric@bktus.com starting on May 12, 2021.
SPDX-License-Identifier: GPL-3.0-or-later
Member Function Documentation
RevSign()
bool GpgFrontend::GpgKeyManager::RevSign (const GpgFrontend::GpgKey & key, const GpgFrontend::SignIdArgsListPtr & signature_id)
Parameters
key
signature_id
Returns
true
false
References GpgFrontend::check_gpg_error(), GpgFrontend::check_gpg_error_2_err_code(), and GpgFrontend::SingletonFunctionObject< GpgKeyGetter >::GetInstance().
SetExpire()
bool GpgFrontend::GpgKeyManager::SetExpire (const GpgKey & key, std::unique_ptr< GpgSubKey > & subkey, std::unique_ptr< boost::posix_time::ptime > & expires)
Set the Expire object.
Parameters
key
subkey
expires
Returns
true
false
References GpgFrontend::check_gpg_error(), and GpgFrontend::check_gpg_error_2_err_code().
SetOwnerTrustLevel()
bool GpgFrontend::GpgKeyManager::SetOwnerTrustLevel (const GpgKey & key, int trust_level)
Returns
References GpgFrontend::check_gpg_error_2_err_code(), GpgFrontend::GpgKey::GetFingerprint(), and GpgFrontend::GpgKey::GetId().
SignKey()
bool GpgFrontend::GpgKeyManager::SignKey (const GpgKey & target, GpgFrontend::KeyArgsList & keys, const std::string & uid, const std::unique_ptr< boost::posix_time::ptime > & expires)
Sign a key pair(actually a certain uid)
Parameters
target target key pair
uid target
expires expire date and time of the signature
Returns
if successful
References GpgFrontend::check_gpg_error(), GpgFrontend::check_gpg_error_2_err_code(), GpgFrontend::SingletonFunctionObject< GpgBasicOperator >::GetInstance(), and GpgFrontend::GpgBasicOperator::SetSigners().
Member Data Documentation
ctx_
GpgContext& GpgFrontend::GpgKeyManager::ctx_ [private]
Initial value:
=
      GpgContext::GetInstance(SingletonFunctionObject::GetChannel())
The documentation for this class was generated from the following files:
src/core/function/gpg/GpgKeyManager.h
src/core/function/gpg/GpgKeyManager.cpp