GpgFrontend::UI::UISignalStation Class Reference
Signals
void SignalKeyDatabaseRefresh ()
void SignalKeyDatabaseRefreshDone ()
void SignalUIRefresh ()
void SignalRefreshInfoBoard (const QString &text, InfoBoardStatus verify_label_status)
void SignalRefreshStatusBar (const QString &message, int timeout)
void SignalNeedUserInputPassphrase (QSharedPointer< GpgPassphraseContext >)
void SignalUserInputPassphraseCallback (QSharedPointer< GpgPassphraseContext >)
void SignalRestartApplication (int)
Static Public Member Functions
static auto GetInstance () -> UISignalStation *
Get the Instance object.
Static Private Attributes
static std::unique_ptr< UISignalStation > instance = nullptr
Member Function Documentation
GetInstance()
auto GpgFrontend::UI::UISignalStation::GetInstance () -> UISignalStation* [static]
Get the Instance object.
Returns
SignalStation*
Referenced by GpgFrontend::UI::CommonUtils::CommonUtils(), GpgFrontend::UI::SetOwnerTrustLevel::Exec(), GpgFrontend::UI::GnuPGControllerDialog::GnuPGControllerDialog(), GpgFrontend::UI::InfoBoardWidget::InfoBoardWidget(), GpgFrontend::UI::InitGpgFrontendUI(), GpgFrontend::UI::KeyGenDialog::KeyGenDialog(), GpgFrontend::UI::KeyMgmt::KeyMgmt(), GpgFrontend::UI::KeyNewUIDDialog::KeyNewUIDDialog(), GpgFrontend::UI::KeyPairDetailTab::KeyPairDetailTab(), GpgFrontend::UI::KeyPairOperaTab::KeyPairOperaTab(), GpgFrontend::UI::KeyPairSubkeyTab::KeyPairSubkeyTab(), GpgFrontend::UI::KeyPairUIDTab::KeyPairUIDTab(), GpgFrontend::UI::KeyServerImportDialog::KeyServerImportDialog(), GpgFrontend::UI::KeyUIDSignDialog::KeyUIDSignDialog(), and GpgFrontend::UI::SubkeyGenerateDialog::slot_key_gen_accept().
SignalRefreshInfoBoard
void GpgFrontend::UI::UISignalStation::SignalRefreshInfoBoard (const QString & text, InfoBoardStatus verify_label_status) [signal]
Parameters
text
verify_label_status
Referenced by GpgFrontend::UI::InfoBoardWidget::InfoBoardWidget().
SignalRefreshStatusBar
void GpgFrontend::UI::UISignalStation::SignalRefreshStatusBar (const QString & message, int timeout) [signal]
Parameters
message
timeout
Referenced by GpgFrontend::UI::KeyMgmt::KeyMgmt().
The documentation for this class was generated from the following files:
src/ui/UISignalStation.h
src/ui/UISignalStation.cpp