GpgFrontend::ArchiveFileOperator Class Reference
Static Public Member Functions
static void ListArchive (const QString &archive_path)
static void NewArchive2DataExchanger (const QString &target_directory, std::shared_ptr< GFDataExchanger >, const OperationCallback &cb)
Create a Archive object.
static void ExtractArchiveFromDataExchanger (std::shared_ptr< GFDataExchanger > fd, const QString &target_path, const OperationCallback &cb)
Member Function Documentation
ExtractArchiveFromDataExchanger()
void GpgFrontend::ArchiveFileOperator::ExtractArchiveFromDataExchanger (std::shared_ptr< GFDataExchanger > fd, const QString & target_path, const OperationCallback & cb) [static]
Parameters
archive_path
base_path
References GpgFrontend::RunIOOperaAsync().
Referenced by GpgFrontend::GpgFileOpera::DecryptArchive(), and GpgFrontend::GpgFileOpera::DecryptVerifyArchive().
ListArchive()
void GpgFrontend::ArchiveFileOperator::ListArchive (const QString & archive_path) [static]
Parameters
archive_path
NewArchive2DataExchanger()
void GpgFrontend::ArchiveFileOperator::NewArchive2DataExchanger (const QString & target_directory, std::shared_ptr< GFDataExchanger > exchanger, const OperationCallback & cb) [static]
Create a Archive object.
Parameters
base_path
archive_path
compress
files
References GpgFrontend::RunIOOperaAsync().
Referenced by GpgFrontend::GpgFileOpera::EncryptDerectorySymmetric(), GpgFrontend::GpgFileOpera::EncryptDerectorySymmetricSync(), GpgFrontend::GpgFileOpera::EncryptDirectory(), and GpgFrontend::GpgFileOpera::EncryptSignDirectory().
The documentation for this class was generated from the following files:
core/function/ArchiveFileOperator.h
core/function/ArchiveFileOperator.cpp