GpgFrontend::GpgDecryptResultAnalyse Class Reference
Public Member Functions
GpgDecryptResultAnalyse (GpgError m_error, GpgDecrResult m_result)
Construct a new Decrypt Result Analyse object.
Protected Member Functions
void do_analyse () final
Private Member Functions
void print_recipient (std::stringstream &stream, gpgme_recipient_t recipient)
Private Attributes
GpgError error_
GpgDecrResult result_
Additional Inherited Members
Constructor & Destructor Documentation
GpgDecryptResultAnalyse()
GpgFrontend::GpgDecryptResultAnalyse::GpgDecryptResultAnalyse (GpgError m_error, GpgDecrResult m_result) [explicit]
Construct a new Decrypt Result Analyse object.
Parameters
m_error
m_result
Copyright (C) 2021 Saturneric
This file is part of GpgFrontend.
GpgFrontend is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
GpgFrontend is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with GpgFrontend. If not, see https://www.gnu.org/licenses/.
The initial version of the source code is inherited from the gpg4usb project, which is under GPL-3.0-or-later.
All the source code of GpgFrontend was modified and released by Saturneric eric@bktus.com starting on May 12, 2021.
SPDX-License-Identifier: GPL-3.0-or-later
Member Function Documentation
do_analyse()
void GpgFrontend::GpgDecryptResultAnalyse::do_analyse () [final], [protected], [virtual]
Implements GpgFrontend::GpgResultAnalyse.
print_recipient()
void GpgFrontend::GpgDecryptResultAnalyse::print_recipient (std::stringstream & stream, gpgme_recipient_t recipient) [private]
Parameters
stream
recipient
References GpgFrontend::SingletonFunctionObject< GpgKeyGetter >::GetInstance(), GpgFrontend::GpgKeyGetter::GetKey(), and GpgFrontend::GpgKey::GetName().
The documentation for this class was generated from the following files:
src/core/function/result_analyse/GpgDecryptResultAnalyse.h
src/core/function/result_analyse/GpgDecryptResultAnalyse.cpp