GpgFrontend::GpgFileOpera Class Reference
Public Member Functions
GpgFileOpera (int channel=SingletonFunctionObject::GetDefaultChannel())
Construct a new Gpg File Opera object.
void EncryptFile (const KeyArgsList &keys, const QString &in_path, bool ascii, const QString &out_path, const GpgOperationCallback &cb)
Encrypted file with public key.
auto EncryptFileSync (const KeyArgsList &keys, const QString &in_path, bool ascii, const QString &out_path) -> std::tuple< GpgError, DataObjectPtr >
void EncryptDirectory (const KeyArgsList &keys, const QString &in_path, bool ascii, const QString &out_path, const GpgOperationCallback &cb)
void EncryptFileSymmetric (const QString &in_path, bool ascii, const QString &out_path, const GpgOperationCallback &cb)
Encrypted file symmetrically (with password)
auto EncryptFileSymmetricSync (const QString &in_path, bool ascii, const QString &out_path) -> std::tuple< GpgError, DataObjectPtr >
void EncryptDerectorySymmetric (const QString &in_path, bool ascii, const QString &out_path, const GpgOperationCallback &cb)
auto EncryptDerectorySymmetricSync (const QString &in_path, bool ascii, const QString &out_path) -> std::tuple< GpgError, DataObjectPtr >
void DecryptFile (const QString &in_path, const QString &out_path, const GpgOperationCallback &cb)
auto DecryptFileSync (const QString &in_path, const QString &out_path) -> std::tuple< GpgError, DataObjectPtr >
void DecryptArchive (const QString &in_path, const QString &out_path, const GpgOperationCallback &cb)
void SignFile (const KeyArgsList &keys, const QString &in_path, bool ascii, const QString &out_path, const GpgOperationCallback &cb)
Sign file with private key.
auto SignFileSync (const KeyArgsList &keys, const QString &in_path, bool ascii, const QString &out_path) -> std::tuple< GpgError, DataObjectPtr >
void VerifyFile (const QString &data_path, const QString &sign_path, const GpgOperationCallback &cb)
Verify file with public key.
auto VerifyFileSync (const QString &data_path, const QString &sign_path) -> std::tuple< GpgError, DataObjectPtr >
void EncryptSignFile (const KeyArgsList &keys, const KeyArgsList &signer_keys, const QString &in_path, bool ascii, const QString &out_path, const GpgOperationCallback &cb)
auto EncryptSignFileSync (const KeyArgsList &keys, const KeyArgsList &signer_keys, const QString &in_path, bool ascii, const QString &out_path) -> std::tuple< GpgError, DataObjectPtr >
void EncryptSignDirectory (const KeyArgsList &keys, const KeyArgsList &signer_keys, const QString &in_path, bool ascii, const QString &out_path, const GpgOperationCallback &cb)
void DecryptVerifyFile (const QString &in_path, const QString &out_path, const GpgOperationCallback &cb)
auto DecryptVerifyFileSync (const QString &in_path, const QString &out_path) -> std::tuple< GpgError, DataObjectPtr >
void DecryptVerifyArchive (const QString &in_path, const QString &out_path, const GpgOperationCallback &cb)
Private Attributes
GpgContext & ctx_
Corresponding context.
Additional Inherited Members
Constructor & Destructor Documentation
GpgFileOpera()
GpgFrontend::GpgFileOpera::GpgFileOpera (int channel = SingletonFunctionObject::GetDefaultChannel()) [explicit]
Construct a new Gpg File Opera object.
Parameters
channel
Member Function Documentation
DecryptArchive()
void GpgFrontend::GpgFileOpera::DecryptArchive (const QString & in_path, const QString & out_path, const GpgOperationCallback & cb)
Parameters
in_path
out_path
cb
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::ArchiveFileOperator::ExtractArchiveFromDataExchanger(), and GpgFrontend::RunGpgOperaAsync().
DecryptFile()
void GpgFrontend::GpgFileOpera::DecryptFile (const QString & in_path, const QString & out_path, const GpgOperationCallback & cb)
Parameters
in_path
out_path
result
Returns
GpgError
References GpgFrontend::CheckGpgError(), ctx_, and GpgFrontend::RunGpgOperaAsync().
DecryptFileSync()
auto GpgFrontend::GpgFileOpera::DecryptFileSync (const QString & in_path, const QString & out_path) -> std::tuple<GpgError, DataObjectPtr>
Parameters
in_path
out_path
cb
Returns
std::tuple<GpgError, DataObjectPtr>
References GpgFrontend::CheckGpgError(), and GpgFrontend::RunGpgOperaSync().
DecryptVerifyArchive()
void GpgFrontend::GpgFileOpera::DecryptVerifyArchive (const QString & in_path, const QString & out_path, const GpgOperationCallback & cb)
Parameters
in_path
out_path
cb
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::ArchiveFileOperator::ExtractArchiveFromDataExchanger(), and GpgFrontend::RunGpgOperaAsync().
DecryptVerifyFile()
void GpgFrontend::GpgFileOpera::DecryptVerifyFile (const QString & in_path, const QString & out_path, const GpgOperationCallback & cb)
Parameters
in_path
out_path
decr_res
verify_res
Returns
GpgError
References GpgFrontend::CheckGpgError(), ctx_, and GpgFrontend::RunGpgOperaAsync().
DecryptVerifyFileSync()
auto GpgFrontend::GpgFileOpera::DecryptVerifyFileSync (const QString & in_path, const QString & out_path) -> std::tuple<GpgError, DataObjectPtr>
Parameters
in_path
out_path
References GpgFrontend::CheckGpgError(), and GpgFrontend::RunGpgOperaSync().
EncryptDerectorySymmetric()
void GpgFrontend::GpgFileOpera::EncryptDerectorySymmetric (const QString & in_path, bool ascii, const QString & out_path, const GpgOperationCallback & cb)
Parameters
in_path
ascii
out_path
cb
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::ArchiveFileOperator::NewArchive2DataExchanger(), and GpgFrontend::RunGpgOperaAsync().
EncryptDerectorySymmetricSync()
auto GpgFrontend::GpgFileOpera::EncryptDerectorySymmetricSync (const QString & in_path, bool ascii, const QString & out_path) -> std::tuple<GpgError, DataObjectPtr>
Parameters
in_path
ascii
out_path
References GpgFrontend::CheckGpgError(), GpgFrontend::ArchiveFileOperator::NewArchive2DataExchanger(), and GpgFrontend::RunGpgOperaSync().
EncryptDirectory()
void GpgFrontend::GpgFileOpera::EncryptDirectory (const KeyArgsList & keys, const QString & in_path, bool ascii, const QString & out_path, const GpgOperationCallback & cb)
Parameters
keys
in_path
ascii
out_path
cb
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::ArchiveFileOperator::NewArchive2DataExchanger(), and GpgFrontend::RunGpgOperaAsync().
EncryptFile()
void GpgFrontend::GpgFileOpera::EncryptFile (const KeyArgsList & keys, const QString & in_path, bool ascii, const QString & out_path, const GpgOperationCallback & cb)
Encrypted file with public key.
Parameters
keys Used public key
in_path The path where the enter file is located
out_path The path where the output file is located
result Encrypted results
channel Channel in context
Returns
unsigned int error code
References GpgFrontend::CheckGpgError(), ctx_, and GpgFrontend::RunGpgOperaAsync().
EncryptFileSymmetric()
void GpgFrontend::GpgFileOpera::EncryptFileSymmetric (const QString & in_path, bool ascii, const QString & out_path, const GpgOperationCallback & cb)
Encrypted file symmetrically (with password)
Parameters
in_path
out_path
result
channel
Returns
unsigned int
References GpgFrontend::CheckGpgError(), ctx_, and GpgFrontend::RunGpgOperaAsync().
EncryptFileSymmetricSync()
auto GpgFrontend::GpgFileOpera::EncryptFileSymmetricSync (const QString & in_path, bool ascii, const QString & out_path) -> std::tuple<GpgError, DataObjectPtr>
Parameters
in_path
ascii
out_path
cb
References GpgFrontend::CheckGpgError(), and GpgFrontend::RunGpgOperaSync().
EncryptFileSync()
auto GpgFrontend::GpgFileOpera::EncryptFileSync (const KeyArgsList & keys, const QString & in_path, bool ascii, const QString & out_path) -> std::tuple<GpgError, DataObjectPtr>
Parameters
keys
in_path
ascii
out_path
Returns
std::tuple<GpgError, DataObjectPtr>
References GpgFrontend::CheckGpgError(), and GpgFrontend::RunGpgOperaSync().
EncryptSignDirectory()
void GpgFrontend::GpgFileOpera::EncryptSignDirectory (const KeyArgsList & keys, const KeyArgsList & signer_keys, const QString & in_path, bool ascii, const QString & out_path, const GpgOperationCallback & cb)
Parameters
keys
signer_keys
in_path
ascii
out_path
cb
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::SingletonFunctionObject< GpgBasicOperator >::GetInstance(), GpgFrontend::ArchiveFileOperator::NewArchive2DataExchanger(), and GpgFrontend::RunGpgOperaAsync().
EncryptSignFile()
void GpgFrontend::GpgFileOpera::EncryptSignFile (const KeyArgsList & keys, const KeyArgsList & signer_keys, const QString & in_path, bool ascii, const QString & out_path, const GpgOperationCallback & cb)
Parameters
keys
signer_keys
in_path
ascii
out_path
cb
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::SingletonFunctionObject< GpgBasicOperator >::GetInstance(), and GpgFrontend::RunGpgOperaAsync().
EncryptSignFileSync()
auto GpgFrontend::GpgFileOpera::EncryptSignFileSync (const KeyArgsList & keys, const KeyArgsList & signer_keys, const QString & in_path, bool ascii, const QString & out_path) -> std::tuple<GpgError, DataObjectPtr>
Parameters
keys
signer_keys
in_path
ascii
out_path
References GpgFrontend::CheckGpgError(), GpgFrontend::SingletonFunctionObject< GpgBasicOperator >::GetInstance(), and GpgFrontend::RunGpgOperaSync().
SignFile()
void GpgFrontend::GpgFileOpera::SignFile (const KeyArgsList & keys, const QString & in_path, bool ascii, const QString & out_path, const GpgOperationCallback & cb)
Sign file with private key.
Parameters
keys
in_path
out_path
result
channel
Returns
GpgError
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::SingletonFunctionObject< GpgBasicOperator >::GetInstance(), and GpgFrontend::RunGpgOperaAsync().
SignFileSync()
auto GpgFrontend::GpgFileOpera::SignFileSync (const KeyArgsList & keys, const QString & in_path, bool ascii, const QString & out_path) -> std::tuple<GpgError, DataObjectPtr>
Parameters
keys
in_path
ascii
out_path
Returns
std::tuple<GpgError, DataObjectPtr>
References GpgFrontend::CheckGpgError(), GpgFrontend::SingletonFunctionObject< GpgBasicOperator >::GetInstance(), and GpgFrontend::RunGpgOperaSync().
VerifyFile()
void GpgFrontend::GpgFileOpera::VerifyFile (const QString & data_path, const QString & sign_path, const GpgOperationCallback & cb)
Verify file with public key.
Parameters
data_path The path where the enter file is located
sign_path The path where the signature file is located
result Verify results
channel Channel in context
Returns
GpgError
References GpgFrontend::CheckGpgError(), ctx_, and GpgFrontend::RunGpgOperaAsync().
VerifyFileSync()
auto GpgFrontend::GpgFileOpera::VerifyFileSync (const QString & data_path, const QString & sign_path) -> std::tuple<GpgError, DataObjectPtr>
Parameters
data_path
sign_path
Returns
std::tuple<GpgError, DataObjectPtr>
References GpgFrontend::CheckGpgError(), and GpgFrontend::RunGpgOperaSync().
Member Data Documentation
ctx_
GpgContext& GpgFrontend::GpgFileOpera::ctx_ [private]
Initial value:
= GpgContext::GetInstance(
      SingletonFunctionObject::GetChannel())
Corresponding context.
Referenced by DecryptArchive(), DecryptFile(), DecryptVerifyArchive(), DecryptVerifyFile(), EncryptDerectorySymmetric(), EncryptDirectory(), EncryptFile(), EncryptFileSymmetric(), EncryptSignDirectory(), EncryptSignFile(), SignFile(), and VerifyFile().
The documentation for this class was generated from the following files:
src/core/function/gpg/GpgFileOpera.h
src/core/function/gpg/GpgFileOpera.cpp