GpgFrontend::UI::InfoTab Class Reference
Class containing the main tab of about dialog.
#include <AboutDialog.h>
Public Member Functions
InfoTab (QWidget *parent=nullptr)
Construct a new Info Tab object.
Detailed Description
Class containing the main tab of about dialog.
Constructor & Destructor Documentation
InfoTab()
GpgFrontend::UI::InfoTab::InfoTab (QWidget * parent = nullptr) [explicit]
Construct a new Info Tab object.
Parameters
parent
References GpgFrontend::GetProjectBuildGitVersion(), GpgFrontend::GetProjectBuildTimestamp(), and GpgFrontend::GetProjectVersion().
The documentation for this class was generated from the following files:
ui/dialog/help/AboutDialog.h
ui/dialog/help/AboutDialog.cpp