GpgFrontend::GpgAdvancedOperator Class Reference
Static Public Member Functions
static void ClearGpgPasswordCache (OperationCallback)
static void ReloadGpgComponents (OperationCallback)
static void RestartGpgComponents ()
static void ResetConfigures (OperationCallback)
static void StartGpgAgent (OperationCallback)
static void StartDirmngr (OperationCallback)
static void StartKeyBoxd (OperationCallback)
Member Function Documentation
ClearGpgPasswordCache()
void GpgFrontend::GpgAdvancedOperator::ClearGpgPasswordCache (OperationCallback cb) [static]
Returns
true
false
Copyright (C) 2021 Saturneric eric@bktus.com
This file is part of GpgFrontend.
GpgFrontend is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
GpgFrontend is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with GpgFrontend. If not, see https://www.gnu.org/licenses/.
The initial version of the source code is inherited from the gpg4usb project, which is under GPL-3.0-or-later.
All the source code of GpgFrontend was modified and released by Saturneric eric@bktus.com starting on May 12, 2021.
SPDX-License-Identifier: GPL-3.0-or-later
References GpgFrontend::GpgCommandExecutor::ExecuteSync().
Referenced by GpgFrontend::ShutdownGlobalBasicalEnv().
ReloadGpgComponents()
void GpgFrontend::GpgAdvancedOperator::ReloadGpgComponents (OperationCallback cb) [static]
Returns
true
false
References GpgFrontend::GpgCommandExecutor::ExecuteSync().
ResetConfigures()
void GpgFrontend::GpgAdvancedOperator::ResetConfigures (OperationCallback cb) [static]
Returns
true
false
References GpgFrontend::GpgCommandExecutor::ExecuteSync().
RestartGpgComponents()
void GpgFrontend::GpgAdvancedOperator::RestartGpgComponents () [static]
Returns
true
false
References GpgFrontend::GpgCommandExecutor::ExecuteSync(), and GpgFrontend::Module::UpsertRTValue().
StartDirmngr()
void GpgFrontend::GpgAdvancedOperator::StartDirmngr (OperationCallback cb) [static]
Returns
true
false
References GpgFrontend::GpgCommandExecutor::ExecuteSync().
StartGpgAgent()
void GpgFrontend::GpgAdvancedOperator::StartGpgAgent (OperationCallback cb) [static]
Returns
true
false
References GpgFrontend::GpgCommandExecutor::ExecuteSync().
StartKeyBoxd()
void GpgFrontend::GpgAdvancedOperator::StartKeyBoxd (OperationCallback cb) [static]
Returns
true
false
References GpgFrontend::GpgCommandExecutor::ExecuteSync().
The documentation for this class was generated from the following files:
src/core/function/gpg/GpgAdvancedOperator.h
src/core/function/gpg/GpgAdvancedOperator.cpp