GpgFrontend::GpgBasicOperator Class Reference
Basic operation collection.
#include <GpgBasicOperator.h>
Public Member Functions
GpgBasicOperator (int channel=SingletonFunctionObject::GetDefaultChannel())
Construct a new Basic Operator object.
void Encrypt (const KeyArgsList &, const GFBuffer &, bool, const GpgOperationCallback &)
auto EncryptSync (const KeyArgsList &, const GFBuffer &, bool) -> std::tuple< GpgError, DataObjectPtr >
void EncryptSymmetric (const GFBuffer &in_buffer, bool ascii, const GpgOperationCallback &cb)
Call the interface provided by GPGME to symmetrical encryption.
auto EncryptSymmetricSync (const GFBuffer &in_buffer, bool ascii) -> std::tuple< GpgError, DataObjectPtr >
void EncryptSign (const KeyArgsList &keys, const KeyArgsList &signers, const GFBuffer &in_buffer, bool ascii, const GpgOperationCallback &cb)
Call the interface provided by gpgme to perform encryption and signature operations at the same time.
auto EncryptSignSync (const KeyArgsList &keys, const KeyArgsList &signers, const GFBuffer &in_buffer, bool ascii) -> std::tuple< GpgError, DataObjectPtr >
void Decrypt (const GFBuffer &in_buffer, const GpgOperationCallback &cb)
Call the interface provided by gpgme for decryption operation.
auto DecryptSync (const GFBuffer &in_buffer) -> std::tuple< GpgError, DataObjectPtr >
void DecryptVerify (const GFBuffer &in_buffer, const GpgOperationCallback &cb)
Call the interface provided by gpgme to perform decryption and verification operations at the same time.
auto DecryptVerifySync (const GFBuffer &in_buffer) -> std::tuple< GpgError, DataObjectPtr >
void Verify (const GFBuffer &in_buffer, const GFBuffer &sig_buffer, const GpgOperationCallback &cb)
Call the interface provided by gpgme for verification operation.
auto VerifySync (const GFBuffer &in_buffer, const GFBuffer &sig_buffer) -> std::tuple< GpgError, DataObjectPtr >
void Sign (const KeyArgsList &signers, const GFBuffer &in_buffer, GpgSignMode mode, bool ascii, const GpgOperationCallback &cb)
Call the interface provided by gpgme for signing operation.
auto SignSync (const KeyArgsList &signers, const GFBuffer &in_buffer, GpgSignMode mode, bool ascii) -> std::tuple< GpgError, DataObjectPtr >
void SetSigners (const KeyArgsList &signers, bool ascii)
Set the private key for signatures, this operation is a global operation.
auto GetSigners (bool ascii) -> std::unique_ptr< KeyArgsList >
Get a global signature private keys that has been set.
Private Attributes
GpgContext & ctx_
Corresponding context.
Additional Inherited Members
Detailed Description
Basic operation collection.
Constructor & Destructor Documentation
GpgBasicOperator()
GpgFrontend::GpgBasicOperator::GpgBasicOperator (int channel = SingletonFunctionObject::GetDefaultChannel()) [explicit]
Construct a new Basic Operator object.
Parameters
channel Channel corresponding to the context
Member Function Documentation
Decrypt()
void GpgFrontend::GpgBasicOperator::Decrypt (const GFBuffer & in_buffer, const GpgOperationCallback & cb)
Call the interface provided by gpgme for decryption operation.
Parameters
in_buffer data that needs to be decrypted
out_buffer decrypted data
result the result of the operation
Returns
error code
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::GpgData::Read2GFBuffer(), and GpgFrontend::RunGpgOperaAsync().
DecryptSync()
auto GpgFrontend::GpgBasicOperator::DecryptSync (const GFBuffer & in_buffer) -> std::tuple<GpgError, DataObjectPtr>
Parameters
in_buffer
References GpgFrontend::CheckGpgError(), GpgFrontend::GpgData::Read2GFBuffer(), and GpgFrontend::RunGpgOperaSync().
DecryptVerify()
void GpgFrontend::GpgBasicOperator::DecryptVerify (const GFBuffer & in_buffer, const GpgOperationCallback & cb)
Call the interface provided by gpgme to perform decryption and verification operations at the same time.
Parameters
in_buffer data to be manipulated
out_buffer data resulting from decryption operation
decrypt_result the result of the decrypting operation
verify_result the result of the verifying operation
Returns
error code
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::GpgData::Read2GFBuffer(), and GpgFrontend::RunGpgOperaAsync().
DecryptVerifySync()
auto GpgFrontend::GpgBasicOperator::DecryptVerifySync (const GFBuffer & in_buffer) -> std::tuple<GpgError, DataObjectPtr>
Parameters
in_buffer
References GpgFrontend::CheckGpgError(), GpgFrontend::GpgData::Read2GFBuffer(), and GpgFrontend::RunGpgOperaSync().
EncryptSign()
void GpgFrontend::GpgBasicOperator::EncryptSign (const KeyArgsList & keys, const KeyArgsList & signers, const GFBuffer & in_buffer, bool ascii, const GpgOperationCallback & cb)
Call the interface provided by gpgme to perform encryption and signature operations at the same time.
Parameters
keys List of public keys
signers Private key for signatures
in_buffer Data for operation
ascii ascii mode
Returns
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::GpgData::Read2GFBuffer(), GpgFrontend::RunGpgOperaAsync(), and SetSigners().
EncryptSignSync()
auto GpgFrontend::GpgBasicOperator::EncryptSignSync (const KeyArgsList & keys, const KeyArgsList & signers, const GFBuffer & in_buffer, bool ascii) -> std::tuple<GpgError, DataObjectPtr>
Parameters
keys
signers
in_buffer
ascii
cb
References GpgFrontend::CheckGpgError(), GpgFrontend::GpgData::Read2GFBuffer(), and GpgFrontend::RunGpgOperaSync().
EncryptSymmetric()
void GpgFrontend::GpgBasicOperator::EncryptSymmetric (const GFBuffer & in_buffer, bool ascii, const GpgOperationCallback & cb)
Call the interface provided by GPGME to symmetrical encryption.
Parameters
in_buffer Data for encryption
out_buffer Encrypted data
result Encrypted results
Returns
GpgError
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::GpgData::Read2GFBuffer(), and GpgFrontend::RunGpgOperaAsync().
EncryptSymmetricSync()
auto GpgFrontend::GpgBasicOperator::EncryptSymmetricSync (const GFBuffer & in_buffer, bool ascii) -> std::tuple<GpgError, DataObjectPtr>
Parameters
in_buffer
ascii
cb
Returns
std::tuple<GpgError, DataObjectPtr>
References GpgFrontend::CheckGpgError(), GpgFrontend::GpgData::Read2GFBuffer(), and GpgFrontend::RunGpgOperaSync().
GetSigners()
auto GpgFrontend::GpgBasicOperator::GetSigners (bool ascii) -> std::unique_ptr<KeyArgsList>
Get a global signature private keys that has been set.
Returns
Intelligent pointer pointing to the private key list
SetSigners()
void GpgFrontend::GpgBasicOperator::SetSigners (const KeyArgsList & signers, bool ascii)
Set the private key for signatures, this operation is a global operation.
Parameters
keys
References GpgFrontend::CheckGpgError(), and ctx_.
Referenced by EncryptSign(), and Sign().
Sign()
void GpgFrontend::GpgBasicOperator::Sign (const KeyArgsList & signers, const GFBuffer & in_buffer, GpgSignMode mode, bool ascii, const GpgOperationCallback & cb)
Call the interface provided by gpgme for signing operation.
The signing modes are as follows: `GPGME_SIG_MODE_NORMAL' A normal signature is made, the output includes the plaintext and the signature. `GPGME_SIG_MODE_DETACH' A detached signature is made. `GPGME_SIG_MODE_CLEAR' A clear text signature is made. The ASCII armor and text mode settings of the context are ignored.
Parameters
signers private keys for signing operations
in_buffer data that needs to be signed
out_buffer verified data
mode signing mode
result the result of the operation
Returns
error code
References GpgFrontend::CheckGpgError(), ctx_, GpgFrontend::GpgData::Read2GFBuffer(), GpgFrontend::RunGpgOperaAsync(), and SetSigners().
SignSync()
auto GpgFrontend::GpgBasicOperator::SignSync (const KeyArgsList & signers, const GFBuffer & in_buffer, GpgSignMode mode, bool ascii) -> std::tuple<GpgError, DataObjectPtr>
Parameters
signers
in_buffer
mode
ascii
cb
Returns
std::tuple<GpgError, DataObjectPtr>
References GpgFrontend::CheckGpgError(), GpgFrontend::GpgData::Read2GFBuffer(), and GpgFrontend::RunGpgOperaSync().
Verify()
void GpgFrontend::GpgBasicOperator::Verify (const GFBuffer & in_buffer, const GFBuffer & sig_buffer, const GpgOperationCallback & cb)
Call the interface provided by gpgme for verification operation.
Parameters
in_buffer data that needs to be verified
out_buffer verified data
result the result of the operation
Returns
error code
References GpgFrontend::CheckGpgError(), ctx_, and GpgFrontend::RunGpgOperaAsync().
VerifySync()
auto GpgFrontend::GpgBasicOperator::VerifySync (const GFBuffer & in_buffer, const GFBuffer & sig_buffer) -> std::tuple<GpgError, DataObjectPtr>
Parameters
in_buffer
sig_buffer
cb
Returns
std::tuple<GpgError, DataObjectPtr>
References GpgFrontend::CheckGpgError(), and GpgFrontend::RunGpgOperaSync().
Member Data Documentation
ctx_
GpgContext& GpgFrontend::GpgBasicOperator::ctx_ [private]
Initial value:
= GpgContext::GetInstance(
      SingletonFunctionObject::GetChannel())
Corresponding context.
Referenced by Decrypt(), DecryptVerify(), EncryptSign(), EncryptSymmetric(), SetSigners(), Sign(), and Verify().
The documentation for this class was generated from the following files:
core/function/gpg/GpgBasicOperator.h
core/function/gpg/GpgBasicOperator.cpp