GpgFrontend::UI::CommonUtils Class Reference
Public Types
using ImportCallbackFunctiopn = std::function< void(const QString &, const QString &, size_t, size_t)>
Public Slots
void SlotImportKeys (QWidget *parent, const QString &in_buffer)
void SlotImportKeyFromFile (QWidget *parent)
void SlotImportKeyFromKeyServer (QWidget *parent)
void SlotImportKeyFromClipboard (QWidget *parent)
static void SlotImportKeyFromKeyServer (const GpgFrontend::KeyIdArgsList &key_ids, const GpgFrontend::UI::CommonUtils::ImportCallbackFunctiopn &callback)
void SlotExecuteGpgCommand (const QStringList &arguments, const std::function< void(QProcess *)> &interact_func)
void SlotExecuteCommand (const QString &cmd, const QStringList &arguments, const std::function< void(QProcess *)> &interact_func)
void SlotRestartApplication (int)
Signals
void SignalKeyStatusUpdated ()
void SignalBadGnupgEnv (QString)
void SignalKeyDatabaseRefreshDone ()
emit when the key database is refreshed
void SignalRestartApplication (int)
Public Member Functions
CommonUtils ()
Construct a new Common Utils object.
bool isApplicationNeedRestart ()
bool KeyExistsinFavouriteList (const GpgKey &key)
void AddKey2Favourtie (const GpgKey &key)
void RemoveKeyFromFavourite (const GpgKey &key)
void ImportKeyFromKeyServer (const KeyIdArgsList &)
Static Public Member Functions
static CommonUtils * GetInstance ()
Get the Instance object.
static void WaitForOpera (QWidget *parent, const QString &, const OperaWaitingCb &)
static void RaiseMessageBox (QWidget *parent, GpgError err)
static void RaiseFailureMessageBox (QWidget *parent, GpgError err)
Private Slots
void slot_update_key_status ()
update the key status when signal is emitted
void slot_update_key_from_server_finished (bool, QString, QByteArray, std::shared_ptr< GpgImportInformation >)
Private Attributes
bool application_need_to_restart_at_once_ = false
Static Private Attributes
static std::unique_ptr< CommonUtils > instance_ = nullptr
Member Function Documentation
GetInstance()
auto GpgFrontend::UI::CommonUtils::GetInstance () [static]
Get the Instance object.
Returns
CommonUtils*
Referenced by GpgFrontend::UI::KeyMgmt::create_actions(), GpgFrontend::UI::InitGpgFrontendUI(), GpgFrontend::UI::MainWindow::refresh_keys_from_key_server(), GpgFrontend::UI::RunGpgFrontendUI(), and GpgFrontend::UI::MainWindow::slot_import_key_from_edit().
RaiseFailureMessageBox()
void GpgFrontend::UI::CommonUtils::RaiseFailureMessageBox (QWidget * parent, GpgError err) [static]
Parameters
err
References GpgFrontend::CheckGpgError2ErrCode(), and GpgFrontend::DescribeGpgErrCode().
Referenced by RaiseMessageBox().
RaiseMessageBox()
void GpgFrontend::UI::CommonUtils::RaiseMessageBox (QWidget * parent, GpgError err) [static]
Parameters
err
References GpgFrontend::CheckGpgError2ErrCode(), GpgFrontend::DescribeGpgErrCode(), and RaiseFailureMessageBox().
Referenced by GpgFrontend::UI::MainWindow::slot_append_selected_keys(), GpgFrontend::UI::KeyPairOperaTab::slot_export_private_key(), GpgFrontend::UI::KeyGenDialog::slot_key_gen_accept(), and GpgFrontend::UI::SubkeyGenerateDialog::slot_key_gen_accept().
SlotExecuteCommand
void GpgFrontend::UI::CommonUtils::SlotExecuteCommand (const QString & cmd, const QStringList & arguments, const std::function< void(QProcess *)> & interact_func) [slot]
Parameters
arguments
interact_func
SlotExecuteGpgCommand
void GpgFrontend::UI::CommonUtils::SlotExecuteGpgCommand (const QStringList & arguments, const std::function< void(QProcess *)> & interact_func) [slot]
Parameters
arguments
interact_func
SlotImportKeyFromClipboard
void GpgFrontend::UI::CommonUtils::SlotImportKeyFromClipboard (QWidget * parent) [slot]
Parameters
parent
References SlotImportKeys().
Referenced by GpgFrontend::UI::KeyMgmt::create_actions().
SlotImportKeyFromFile
void GpgFrontend::UI::CommonUtils::SlotImportKeyFromFile (QWidget * parent) [slot]
Parameters
parent
References GpgFrontend::ReadFile(), and SlotImportKeys().
Referenced by GpgFrontend::UI::KeyMgmt::create_actions().
SlotImportKeyFromKeyServer [1/2]
void GpgFrontend::UI::CommonUtils::SlotImportKeyFromKeyServer (const GpgFrontend::KeyIdArgsList & key_ids, const GpgFrontend::UI::CommonUtils::ImportCallbackFunctiopn & callback) [static], [slot]
Parameters
ctx_channel
key_ids
callback
References GpgFrontend::SingletonFunctionObject< GpgKeyImportExporter >::GetInstance().
SlotImportKeyFromKeyServer [2/2]
void GpgFrontend::UI::CommonUtils::SlotImportKeyFromKeyServer (QWidget * parent) [slot]
Parameters
parent
Referenced by GpgFrontend::UI::KeyMgmt::create_actions().
SlotImportKeys
void GpgFrontend::UI::CommonUtils::SlotImportKeys (QWidget * parent, const QString & in_buffer) [slot]
Parameters
parent
in_buffer
References GpgFrontend::SingletonFunctionObject< GpgKeyImportExporter >::GetInstance().
Referenced by GpgFrontend::UI::MainWindow::slot_import_key_from_edit(), SlotImportKeyFromClipboard(), and SlotImportKeyFromFile().
WaitForOpera()
void GpgFrontend::UI::CommonUtils::WaitForOpera (QWidget * parent, const QString & waiting_dialog_title, const OperaWaitingCb & opera) [static]
Parameters
err
Referenced by GpgFrontend::UI::KeyGenDialog::slot_key_gen_accept(), GpgFrontend::UI::SubkeyGenerateDialog::slot_key_gen_accept(), GpgFrontend::UI::MainWindow::SlotArchiveDecrypt(), GpgFrontend::UI::MainWindow::SlotArchiveDecryptVerify(), GpgFrontend::UI::MainWindow::SlotDecrypt(), GpgFrontend::UI::MainWindow::SlotDecryptVerify(), GpgFrontend::UI::MainWindow::SlotDirectoryEncryptSign(), GpgFrontend::UI::MainWindow::SlotEncrypt(), GpgFrontend::UI::MainWindow::SlotEncryptSign(), GpgFrontend::UI::MainWindow::SlotFileDecrypt(), GpgFrontend::UI::MainWindow::SlotFileDecryptVerify(), GpgFrontend::UI::MainWindow::SlotFileEncrypt(), GpgFrontend::UI::MainWindow::SlotFileEncryptSign(), GpgFrontend::UI::MainWindow::SlotFileSign(), GpgFrontend::UI::MainWindow::SlotFileVerify(), GpgFrontend::UI::MainWindow::SlotSign(), and GpgFrontend::UI::MainWindow::SlotVerify().
The documentation for this class was generated from the following files:
src/ui/UserInterfaceUtils.h
src/ui/UserInterfaceUtils.cpp