GpgFrontend::GpgCommandExecutor Class Reference
Extra commands related to GPG.
#include <GpgCommandExecutor.h>
Classes
struct ExecuteContext
Public Types
using ExecuteContexts = QList< ExecuteContext >
Static Public Member Functions
static void ExecuteSync (ExecuteContext)
Excuting a command.
static void ExecuteConcurrentlyAsync (ExecuteContexts)
static void ExecuteConcurrentlySync (ExecuteContexts)
Detailed Description
Extra commands related to GPG.
Member Function Documentation
ExecuteSync()
void GpgFrontend::GpgCommandExecutor::ExecuteSync (ExecuteContext context) [static]
Excuting a command.
Parameters
arguments Command parameters
interact_func Command answering function
References GpgFrontend::SingletonFunctionObject< TaskRunnerGetter >::GetInstance().
Referenced by GpgFrontend::GpgAdvancedOperator::ClearGpgPasswordCache(), GpgFrontend::GpgKeyOpera::GenerateRevokeCert(), GpgFrontend::GpgAdvancedOperator::ReloadGpgComponents(), GpgFrontend::GpgAdvancedOperator::ResetConfigures(), GpgFrontend::GpgAdvancedOperator::RestartGpgComponents(), GpgFrontend::GpgAdvancedOperator::StartDirmngr(), GpgFrontend::GpgAdvancedOperator::StartGpgAgent(), and GpgFrontend::GpgAdvancedOperator::StartKeyBoxd().
The documentation for this class was generated from the following files:
core/function/gpg/GpgCommandExecutor.h
core/function/gpg/GpgCommandExecutor.cpp