GpgFrontend::UI::KeyTable Struct Reference
Public Types
using KeyTableFilter = std::function< bool(const GpgKey &, const KeyTable &)>
Signals
void SignalColumnTypeChange (GpgKeyTableColumn)
Public Member Functions
KeyTable (QWidget *parent, QSharedPointer< GpgKeyTableModel > model, GpgKeyTableDisplayMode _select_type, GpgKeyTableColumn _info_type, GpgKeyTableProxyModel::KeyFilter _filter=[](const GpgKey &) -> bool { return true;})
Construct a new Key Table object.
void RefreshModel (QSharedPointer< GpgKeyTableModel > model)
auto GetChecked () const -> KeyIdArgsListPtr
Get the Checked object.
void UncheckALL () const
void CheckALL () const
void SetFilterKeyword (const QString &keyword)
auto IsRowChecked (int row) const -> bool
void SetRowChecked (int row) const
Set the Row Checked object.
auto GetRowSelected () const -> int
Set the Row Checked object.
auto GetRowCount () const -> int
Get the Row Count object.
auto GetKeyIdByRow (int row) const -> QString
Get the Key Id By Row object.
auto IsPublicKeyByRow (int row) const -> bool
auto IsPrivateKeyByRow (int row) const -> bool
void CheckAll ()
void UncheckAll ()
Private Attributes
QSharedPointer< GpgKeyTableModel > model_
GpgKeyTableProxyModel proxy_model_
GpgKeyTableColumn column_filter_
Constructor & Destructor Documentation
KeyTable()
GpgFrontend::UI::KeyTable::KeyTable (QWidget * parent, QSharedPointer< GpgKeyTableModel > model, GpgKeyTableDisplayMode _select_type, GpgKeyTableColumn _info_type, GpgKeyTableProxyModel::KeyFilter _filter = [](const GpgKey&) -> bool { return true; })
Construct a new Key Table object.
Parameters
_key_list
_select_type
_info_type
_filter
References GpgFrontend::UI::CommonUtils::GetInstance(), GpgFrontend::SingletonFunctionObject< GpgKeyGetter >::GetInstance(), and GetKeyIdByRow().
Member Function Documentation
GetChecked()
auto GpgFrontend::UI::KeyTable::GetChecked () const -> KeyIdArgsListPtr
Get the Checked object.
Returns
KeyIdArgsListPtr&
References GetKeyIdByRow(), GetRowCount(), and IsRowChecked().
GetKeyIdByRow()
auto GpgFrontend::UI::KeyTable::GetKeyIdByRow (int row) const -> QString
Get the Key Id By Row object.
Parameters
row
Returns
QString
Referenced by GetChecked(), KeyTable(), and GpgFrontend::UI::KeyList::SetChecked().
GetRowCount()
auto GpgFrontend::UI::KeyTable::GetRowCount () const -> int
Get the Row Count object.
Returns
auto
Referenced by GetChecked(), and GpgFrontend::UI::KeyList::SetChecked().
GetRowSelected()
auto GpgFrontend::UI::KeyTable::GetRowSelected () const -> int
Set the Row Checked object.
Parameters
row
IsPrivateKeyByRow()
auto GpgFrontend::UI::KeyTable::IsPrivateKeyByRow (int row) const -> bool
Parameters
row
Returns
true
false
IsPublicKeyByRow()
auto GpgFrontend::UI::KeyTable::IsPublicKeyByRow (int row) const -> bool
Parameters
row
Returns
true
false
IsRowChecked()
auto GpgFrontend::UI::KeyTable::IsRowChecked (int row) const -> bool
Parameters
row
Returns
true
false
Referenced by GetChecked().
RefreshModel()
void GpgFrontend::UI::KeyTable::RefreshModel (QSharedPointer< GpgKeyTableModel > model)
Parameters
model
SetRowChecked()
void GpgFrontend::UI::KeyTable::SetRowChecked (int row) const
Set the Row Checked object.
Parameters
row
Referenced by GpgFrontend::UI::KeyList::SetChecked().
The documentation for this struct was generated from the following files:
ui/widgets/KeyTable.h
ui/widgets/KeyTable.cpp